### ISSUE TITLE
table / column comments

### ISSUE THREAD

**Issue by stvowi** [ikkez/f3-schema-builder#1]
Es wäre sehr angenehm, wenn man auch Kommentare für Tabellen/ Spalten bei der Erstellung von Tabellen/ Spalten angeben könnte.

**Comment by ikkez** [comment]
Reicht es nicht, wenn man die Kommentare einfach im Controller oder einer eigenen config Datei erfasst, in der man Tabellen definiert? Also als php oder ini comment. Nach einer kurzen Suche sieht die Landschaft sehr unterschiedlich aus:
-  MySQL: einfach zu definieren in der Tabellendefinition, und change column
-  sqlite: geht gar nicht
-  sql Server: nur über Prozeduren zu machen
-  postgre: über interne comments Tabelle zu pflegen

Das könnte ein wenig aufwändig werden das einzubauen.

**Comment by doksides** [comment]
Foreign key support?

**Comment by ikkez** [comment]
nope. not yet integrated but there is a schema builder plugin from @exodus4d right here https://github.com/ikkez/f3-cortex/issues/9#issuecomment-166794589

**Comment by stvowi** [comment]
Thre is no schema builder plugin by github from @exodus4d. Do you know a download link?

**Comment by ikkez** [comment]
Link is in his comment.
