### ISSUE TITLE
TODO: check that condition

### ISSUE THREAD

**Issue by stvowi** [ikkez/f3-schema-builder#2]
In Zeile 1123 steht: if ($this->type != 'TIMESTAMP' && // TODO: check that condition

Würden Sie bitte Ihr Werk vollenden? Ich verwende Ihren Quellcode für ein ernsthaftes Projekt.

**Comment by ikkez** [comment]
Ich hab mal reingeschaut. Die Zeile an sich macht kein Problem. Hier findet nur eine Prüfung des Spaltentyps statt, um sicher zu gehen das der Zeitstempel Standardwert an dieser Stelle auch korrekt konfiguriert ist. Die Notiz erinnert mich nur daran zu prüfen ob evtl irgendwelche Spezial-Zeitfelder korrekt erkannt werden, sofern man eine bestehende Datenbank bearbeitet. Aber selbst dann wäre dies hier kein Problem. Ich überleg ob ich die Zeile nicht auch einfach rausnehmen kann.

**Comment by stvowi** [comment]
Ich hatte bisher kein Problem damit. Danke für die Antwort!
