### ISSUE TITLE
[help wanted] Reverse dataType mapping

### ISSUE THREAD

**Issue by exodus4d** [ikkez/f3-schema-builder#3]
I´m currently working on a database update/setup feature for my app. I would like to create a small UI that shows all [_Cortex_](https://github.com/ikkez/f3-cortex) models with their `$fieldConf` configuration, like `type`, `index`, `default` ,... information (something similar to [_PHPMyAdmin_](http://demo.phpmyadmin.net/master-config/) ). Moreover I want to compare the model `$fieldConf` settings with the "_Current_" existing table (MySQL) columns.
##### Some examples:
- If a column exists in the model but not in MySQL, it is marked with a red cross (X)
- If a column `dataType` has changed on an existing MySQL column (e.g. `Schema::DT_VARCHAR128` to `Schema::DT_VARCHAR256`), the current `dataType` is marked in orange,...
##### My approach:

I have a static array with all  model classes, which i loop over to get the `New/Updated` $fieldConf` for each model:

```
$requiredTables = [];

foreach($dbData['models'] as $model){
    $tableConfig =  call_user_func($model . '::resolveConfiguration');
    $requiredTables[$tableConfig['table']] = [
        'fieldConf' => $tableConfig['fieldConf'],
         'exists' => false
    ];
}
```

... and i have an other array with the `Current` tables in the database ...

```
$schema = new SQL\Schema($db);
$currentTables = $schema->getTables();
```

... now i can do a nested loop over both arrays and check  if a table already exists. If it does, i can compare the column definition and check for changes...

```
foreach($requiredTables as $requiredTableName => $data){
    if(in_array($requiredTableName, $currentTables)){
        // table exists

        // get column definition
        $tableModifier = new SQL\TableModifier($requiredTableName, $schema);
        $currentColumns = $tableModifier->getCols(true);

        foreach($data['fieldConf'] as $columnName => $fieldConf){
            if(array_key_exists($columnName, $currentColumns)){
                // column exists -> check colum type for changes...
                // -> THE PROBLEM :)

            }else{
                // column not exists OR is not required e.g. "virtual Field"
            }
        }

    }
}
```
##### The Problem

For a column `type` check for changes, i could compare `$currentColumns[$columnName]['type']` (which is a MySQL type definition e.g. "tinyint(1)" ) with `$fieldConf['type']` (which is a `DB\SQL\Schema::DT_BOOL` type definition e.g. "BOOLEAN").

But the column type actually hasn´t changed at all :)
What i need at this point is some kind of "reverse Schema mapping" that either converts "tinyint(1)" into "BOOLEAN" (which is probably not always a good idea) _OR_ "BOOLEAN" into "tinyint(1)" to make a column type check possible :)
##### The Question
1. Is there a simpler/more elegant way to achieve what i want?
2. Can i use something (already existing) from _Schema Builder_?

---

Sorry for the wall of text, I hope it is understandable ;) Great work at all!
##### Here is small preview of the current state:

![DB Diff. UI](http://i.imgur.com/HsiFC2t.png)

**Comment by ikkez** [comment]
hi. very nice idea, looks great.
Your approach is totally right. I think way to go is to compare the resolved datatype value from `BOOLEAN` with the table's current datatype (`tinyint(1)`). To resolve the Schema `BOOLEAN` label, you could usually use the [findQuery()](https://github.com/ikkez/f3-schema-builder/blob/master/lib/db/sql/schema.php#L1102) method, but the `BOOLEAN` field is some kind of alias in mysql (and maybe others) that converts to `tinyint(1)`. Well maybe it would be the easiest, if we just alter the type for mysql's boolean [here](https://github.com/ikkez/f3-schema-builder/blob/master/lib/db/sql/schema.php#L33). I guess findQuery would return tinyint then, which would be comparable.
For other fields which are no alias name in mysql, it should already work with the findQuery method:

``` php
$type_val = $schema->findQuery($schema->dataTypes[strtoupper($type)]);
if (!preg_match('/'.preg_quote($type_val).'/i',$current_type)) {
// different column datatype found
}

```

**Comment by ikkez** [comment]
I adjusted some data types to resolve any engine specific alias names, added a new `isCompatible` method for easy checking if a type matches, i.e: `$schema->isCompatible('BOOLEAN','tinyint(1)');` and 
added a bunch of tests to be sure that it works:

![screenshot-2015-12-10-08 41 29](https://cloud.githubusercontent.com/assets/1177647/11709913/b74a8540-9f1b-11e5-8c1c-5977d50ca645.jpg)

**Comment by exodus4d** [comment]
Very nice! I spend some hours with testing the new functions. 
I thought it would be nice to improve the `isCompatible()` method and add support for detecting _type length_ as well.
The current problem is, that `VARCHAR256` is compatible to `varchar(128)`. 
The following is just tested on _MySql_ but i tried to make the new _Regex_ type-length check optional (it looks like that some of the length values are _MySql_ specific, e.g. tinyint(1) ).

I changed your code [L294](https://github.com/ikkez/f3-schema-builder/blob/dev-2.2/lib/db/sql/schema.php#L294):

``` php
public function isCompatible($colType,$colDef) {
    $raw_type=$this->findQuery($this->dataTypes[strtoupper($colType)]);
    preg_match('/(\w+(?:\s+\w+)*)/',$raw_type,$match);
    return (bool) preg_match('/'.preg_quote($match[0]).'/i',$colDef);
}
```

.. into this:

``` php
public function isCompatible($colType,$colDef) {
    $raw_type=$this->findQuery($this->dataTypes[strtoupper($colType)]);
    preg_match_all('/(?P<type>\w+)($|\((?P<length>(\d+|(.*)))\))/', $raw_type, $match);
    return (bool) preg_match_all('/'.preg_quote($match['type'][0]).'($|\(' . preg_quote($match['length'][0]) . '\))/i',$colDef);
}
```
- I changed both `preg_match()` to `preg_match_all()` in order to fetch the type-length options (if available)
- I labelled the found matches ('type' and 'length'). So they are always present in `$match` even if there is no `length` found.
- Now we can compare the two column data-types (both _Regex_ expressions are almost identically). The `($| ...` adds the type-length check as optional.

I have tested the regex with some types [demo](https://regex101.com/r/fV6kL3/1).

##### Problem

`Schema::DT_INT` is converted into `INT4` [L122](https://github.com/ikkez/f3-schema-builder/blob/dev-2.2/lib/db/sql/schema.php#L122) which is supposed to be a _MySql_ type of `int` [L48](https://github.com/ikkez/f3-schema-builder/blob/dev-2.2/lib/db/sql/schema.php#L48). But _MySql_ always adds a "default" length of **11** to an int-column if there is no length given [stackoverflow](http://stackoverflow.com/a/5256610).

##### Solution

Can we change the _MySql_ type from `int` to `int(11)` for `INT4`. We should add this as an extra array entry to the `$dataTypes` config, otherwise this will be changed for "mssql|dblib|sybase|odbc|sqlsrv" as well.

**Comment by ikkez** [comment]
sounds reasonable. committed! thanks.

**Comment by ikkez** [comment]
@exodus4d can this be closed now or is still something missing?

**Comment by exodus4d** [comment]
Thanks for all your help ;)
